### ISSUE TITLE
Implement a database system

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#24]
## Description
Select a database system and implement it by intregating it into Django's model.
  - Story points: 1
  - Priority: High
  - Risk: Low

## Tasks
  1. Evaluate different database systems and select the most appropriate.
  1. Install necessary software.
  1. Create a simple webpage that displays sample data from the database.

## Acceptance Test
  1. Open page which displays data from the database.
  1. Notice that a connection to the database is established and data is displayed correctly.

**Comment by alvyn279** [comment]
I personally think that the installed **sqlite3** on our Django application is sufficient for our usage. With all the information of the database stored in one file, it will be easier for the team members to obtain an updated database by the simple command of **git pull <branch-name>**.

### Steps to implement this task:

1. Add an application to the Django project
1. **makemigrations** and **migrate**
1. Create one sample table (class) through **models.py**
1. Create administrator (superuser) for app so that the database can be viewed as a UI at **url/admin**

**Comment by Lercerss** [comment]
# SQLite 
## Pros
  - Very lightweight
  - No complicated setup or configuration
  - Acts like a more sophisticated file system
  - Local only, doesn't need a separate server or complex connections
## Cons
  - Local only, cannot be used to share information across different machines.
  - A few incompatibility issues with Django native support, detailed [here](https://docs.djangoproject.com/en/2.0/ref/databases/#sqlite-notes). Namely, most of the time, searches in strings are done case insensitively.

**Comment by Lercerss** [comment]
# PostgreSQL/MySQL
## Pros
  - Client/Server Architecture
  - More robust for larger datasets
  - Higher concurrency, more connections possible at once
  - More query options and sophisticated SQL functions
## Cons
  - More complicated setup.
  - More dependencies for Python API.
  - Requires more resources

**Comment by Lercerss** [comment]
# MongoDB
## Pros
  - Dictionary based storage, not columns/tables
  - Data stored in JSON-like documents, requiring no schema or migrations
  - Possibility to have the server hosted for free on the cloud
  - 
## Cons
  - Not directly supported by Django
  - No explicit schema in the database
  - More dependencies (installing mongodb Python API)

**Comment by Lercerss** [comment]
Implemented SQLite3.
