### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by pvacca97** [Lercerss/SOEN341W18#27]
## Description
The welcome page will allow the user to log in or sign up to the website. Once logged in, the page will welcome the user and display the latest questions that have been posted.
  - Story points: 2
  - Priority: High
  - Risk: Low

## Tasks
  1. Format page to some sort of style
  1. Add a Sign Up button
  1. Add a Log In button
  1. Display five latest questions

## Acceptance Test
  1. View the page in browser
  1. Verify that the Sign Up button redirects to the Sign Up page
  1. Verify that the Log In button redirects to the the Log In page
  1. View latest questions
  1. Click on the latest questions and ensure that they redirect to its specific thread

**Comment by jetcanfly** [comment]
Hi Patrick, I made a prototype for welcome page on branch: will_login_page cuz I thought that was what TA wants in Sprint 1. I think we could refer to and modify it together. Let's discuss it on Friday.
![login](https://user-images.githubusercontent.com/18118928/35661934-58087948-06e3-11e8-971f-63d245ae609e.png)

**Comment by Lercerss** [comment]
As we have previously discussed, this issue would include adding Bootstrap and other front end dependencies to the project. It would be best to use the available CDN links instead of adding them to our codebase. To do this, I suggest we use the ability to extend templates provided by the Django template engine. [Here is a quick example of using the `extends` tag.](https://gist.github.com/monokrome/5447258) The django templating language is detailed further [here](https://docs.djangoproject.com/en/2.0/topics/templates/#the-django-template-language).
Here we should be taking advantage of a base template that would include the necessary `<link>` tags in the head, then have subtemplates that would extend this base template and always load with the necessary libraries. The "child" templates would contain the bulk of the HTML and code.

**Comment by alvyn279** [comment]
I also believe calling the libraries needed through CDN is the best option, to avoid committing so many lines of codes. @13rinda , this would be aimed to your commit 4f6ea294ef6f24b46945206c0648a6b611e30e5e . Creating a single `base.html` file is a great way to have inheritance in our templates.

**Comment by Lercerss** [comment]
#38 solved this issue.

**Comment by niiita** [comment]
![image](https://user-images.githubusercontent.com/35353909/37231661-f9bc1ab8-23b9-11e8-9ecd-7fa5539699ad.png)
