### ISSUE TITLE
Improve user interface for display of question, comments and answers

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/SOEN341W18#93]
## Description
As a user we want a visually improved positioning and styling of question, answers, and comments  throughout the website for a more natural Q&A feel. Its tasks are strictly front-end. **Some of the current styling makes it hard for the user to intuitively know where to go or what to do.** This was expressed by the TA during evaluation of Sprint 3 deliverable.

  - Story points: 5
  - Priority: High
  - Risk: Low

## Tasks
  1. Minimize or remove completely the banner on each page (with bubbles background)
  1. On `answerspage.html`, clearly delimit the question, answers, and comments from one another. We can inspire ourselves from Q&A websites such as [StackOverflow](https://stackoverflow.com/) and [Reddit](https://www.reddit.com/).

## Acceptance Test
  1. Main components of a page are visible as soon as page loads (no need for scrolling)
  1. Observe that new comments and answers to a question are spawned in their correct relative position
  1. The question, its answers and comments are visibly separated from one another and each post type (i.e. Comment, Answer or Question) is clearly distinguished.

**Comment by Lercerss** [comment]
As mentionned in Task 1 of this story, one of the display issues we are having is that elements placed in the `header` block of our templates take up one full screen in the browser. We could possibly solve this by reducing the size of the `header` block on pages other than the homepage to around 30% of a screen. This would clearly distinguish functional pages such as answers page, login and question index from the homepage. In order to do so we would need to make sure that the `header` block contains minimal information so it can fit into the smaller display size.

**Comment by Lercerss** [comment]
We should propose a sketch/design of what the answers page should look like in order to lead the implementation of the user experience changes.

**Comment by patrickvacca** [comment]
![screenshot from 2018-04-15 18-04-21](https://user-images.githubusercontent.com/35609091/38783944-fbb2ae3c-40d7-11e8-9bd9-dc2ab1ed1099.png)

**Comment by patrickvacca** [comment]
Conversation in PR #116
